apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-smp-affinity-amd64
  namespace: kube-system
  labels:
    tier: node
    app: smpaffinity
spec:
  selector:
    matchLabels:
      name: smp-affinity
  template:
    metadata:
      labels:
        name: smp-affinity
        tier: node
        app: smpaffinity
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: irq-smp-balance-sa
      containers:
      - name: kube-smpaffinity
        image: smp-affinity
        imagePullPolicy: Never
        command:
          - smpaffinity
        env:
          - name: WORKER_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: cpustate
          mountPath: /shared/var/lib/kubelet/
          readOnly: true
        - name: hostirq
          mountPath:  /shared/proc/irq/
          readOnly: false
      volumes:
        - name: cpustate
          hostPath:
            path: /var/lib/kubelet/
        - name: hostirq
          hostPath:
            path: /proc/irq/