apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-smp-affinity-amd64
  namespace: kube-system
  labels:
    tier: node
    app: smpaffinity
spec:
  selector:
    matchLabels:
      name: smp-affinity
  template:
    metadata:
      labels:
        name: smp-affinity
        tier: node
        app: smpaffinity
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: irq-smp-balance-sa
      initContainers:
      - name: irq-daemon-init
        image: smp-affinity
        command: ['cp', '/irqsmpdaemon', '/host/usr/bin/irqsmpdaemon']
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: smpbin
          mountPath: /host/usr/bin
      containers:
      - name: kube-smpaffinity
        image: smp-affinity
        imagePullPolicy: IfNotPresent
        command:
          - smpaffinity
        env:
          - name: WORKER_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: cpustate
          mountPath: /host/var/lib/kubelet/
          readOnly: true
        - name: hostirq
          mountPath:  /host/proc/irq/
        - name: irqbalanceconf
          mountPath:  /host/etc/sysconfig/
      volumes:
        - name: cpustate
          hostPath:
            path: /var/lib/kubelet/
        - name: hostirq
          hostPath:
            path: /proc/irq/
        - name: irqbalanceconf
          hostPath:
            path: /etc/sysconfig/
        - name: smpbin
          hostPath:
            path: /usr/bin/
