apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    irq-load-balancing.docker.io: "true"
spec:
  containers:
  - name: testcontainer
    image:  golang:1.15-alpine
    imagePullPolicy: IfNotPresent
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        cpu: '2'
        memory: 100Mi
      limits:
        cpu: '2'
        memory: 100Mi